- name: SSH | Copy rsa_key for user
  hosts: astra
  become: yes
  tasks:
    - name: Copy id_rsa.pub
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"

- name: SSH | Copy rsa_key for root
  hosts: astra
  become: yes
  tasks:
    - name: Copy root id_rsa.pub
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
