---
- name: CryptoPro | Creates directory
  file:
    path: "{{tmp_dir}}"
    state: directory
  tags:
    - install CryptoPro

- name: CryptoPro | Unpacking deb files
  unarchive:
    src: ../files/linux-amd64_deb.tgz 
    dest: "{{tmp_dir}}"
  tags:
    - install CryptoPro

- name: CryptoPro | Uninstall CryptoPro via sh
  become: true
  ansible.builtin.shell: "{{tmp_dir}}linux-amd64_deb/uninstall.sh"
  tags: 
    - install CryptoPro

#- name: CryptoPro | Install deb packages
#  become: true
#  apt:
#    deb: "{{ item }}"
#    state: present
#  loop: "{{ cryptopro_packages }}"
#  tags:
#     - install

- name: CryptoPro | Install CryptoPro via sh
  become: true
  ansible.builtin.shell: "{{tmp_dir}}linux-amd64_deb/install.sh"
  tags:
    - install CryptoPro

- name: CryptoPro | Creating a path for system utilities CryptoPro
  become_user: "{{user_name}}"
  ansible.builtin.shell: export PATH="$(/bin/ls -d /opt/cprocsp/{s,}bin/*|tr '\n' ':')$PATH"
  tags:
    - customization CryptoPro

#- name: CryptoPro | Install license validity
#  ansible.builtin.shell: sudo /opt/cprocsp/sbin/amd64/cpconfig -license -set {{ lic_lic_cryptopro }}
#  tags:
#    - customization CryptoPro

- name: CryptoPro | Create dirs for user container on remote host
  file:
    path: "/var/opt/cprocsp/keys/{{user_name}}"
    state: directory
    owner: "{{user_name}}"
  when: container_name != ""
  tags:
    - install_certificate

- name: CryptoPro | Copy container's files to remote host
  copy:
    src: ../files/{{container_dir}}
    dest: "/var/opt/cprocsp/keys/{{user_name}}"
    owner: "{{user_name}}"
  when: container_dir != ""
  tags:
    - install_certificate

- name: CryptoPro | Copy certs to remote host
  copy:
    src: ../files/certs
    dest: "{{tmp_dir}}"
  when: cert_dir != ""
  tags:
    - install_certificate

#- name: CryptoPro | Install root cert(s)
#  shell: /opt/cprocsp/bin/amd64/certmgr -inst -all -store mroot -file {{item}}
#  with_items: "{{root_cert}}"
#  when: root_cert is defined
#  tags:
#    - install_certificate

#- name: CryptoPro | Clean tmp dir
#  file:
#    path: "{{tmp_dir}}"
#    state: absent
#  tags:
#    - install

#- name: Clean tmp dir 
#  become: yes
#  files:
#  shell: rm -rf {{tmp_dir}}  

#GitHub
#https://github.com/malkinfedor/ansible_cryptopro.gitsudo /opt/cprocsp/sbin/amd64/cpconfig -license -set <номер_лицензии>sudo /opt/cprocsp/sbin/amd64/cpconfig -license -set <номер_лицензии>
