---
- name: Creates directory
  file:
    path: "{{tmp_dir}}"
    state: directory
  tags:
    - install

- name: Unpacking deb files
  unarchive:
    src: ../files/linux-amd64_deb.tgz 
    dest: "{{tmp_dir}}"
  tags:
    - install

- name: Uninstall CryptoPro via sh
  become: true
  ansible.builtin.shell: "{{tmp_dir}}linux-amd64_deb/uninstall.sh"
  tags: 
    - install

#- name: Install deb packages
#  become: true
#  apt:
#    deb: "{{ item }}"
#    state: present
#  loop: "{{ cryptopro_packages }}"

- name: Install CryptoPro via sh
  become: true
  ansible.builtin.shell: "{{tmp_dir}}linux-amd64_deb/install.sh"

- name: Creating a path for system utilities CryptoPro
  become_user: "{{user_name}}"
  ansible.builtin.shell: export PATH="$(/bin/ls -d /opt/cprocsp/{s,}bin/*|tr '\n' ':')$PATH"

#- name: Install license validity
#  ansible.builtin.shell: sudo /opt/cprocsp/sbin/amd64/cpconfig -license -set <номер_лицензии>

- name: Create dirs for user container on remote host
  file:
    path: "/var/opt/cprocsp/keys/{{user_name}}"
    state: directory
    owner: "{{user_name}}"
  when: container_name != ""
  tags:
    - install_certificate

- name: Copy container's files to remote host
  copy:
    src: ../files/{{container_dir}}
    dest: "/var/opt/cprocsp/keys/{{user_name}}"
    owner: "{{user_name}}"
  when: container_dir != ""
  tags:
    - install_certificate

- name: Copy certs to remote host
  copy:
    src: ../files/certs
    dest: "{{tmp_dir}}"
  when: cert_dir != ""
  tags:
    - install_certificate

#- name: Install root cert(s)
#  shell: /opt/cprocsp/bin/amd64/certmgr -inst -all -store mroot -file {{item}}
#  with_items: "{{root_cert}}"
#  when: root_cert is defined
#  tags:
#    - install_certificate

#- name: Clean tmp dir
#  file:
#    path: "{{tmp_dir}}"
#    state: absent
#  tags:
#    - install

#- name: Clean tmp dir 
#  become: yes
#  files:
#  shell: rm -rf {{tmp_dir}}  

#GitHub
#https://github.com/malkinfedor/ansible_cryptopro.gitsudo /opt/cprocsp/sbin/amd64/cpconfig -license -set <номер_лицензии>sudo /opt/cprocsp/sbin/amd64/cpconfig -license -set <номер_лицензии>
